include:
  - board: nice_nano//zmk
    shield: corne_trackpoint_right
    snippet: zmk-usb-logging
    artifact-name: corne_trackpoint_right-nice_nano-standalone
  - board: nice_nano//zmk
    shield: settings_reset
    snippet: zmk-usb-logging
