CONFIG_ZMK_POINTING=y
CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_ZMK_BLE=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
CONFIG_ZMK_SPLIT_BLE_CENTRAL_POSITION_QUEUE_SIZE=20
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024
CONFIG_ZMK_BLE_MOUSE_REPORT_QUEUE_SIZE=40
CONFIG_ZMK_BLE_KEYBOARD_REPORT_QUEUE_SIZE=40

CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y
CONFIG_KERNEL_SHELL=y
