CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=y
CONFIG_SHELL=y
CONFIG_KERNEL_SHELL=y
CONFIG_LOG=y
CONFIG_BT_PERIPHERAL_PREF_CONN_INTERVAL=12
CONFIG_ZMK_HID_REPORT_QUEUE_SIZE=10
